import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "../app/components/NavBar";
import { SignedIn, SignedOut, auth } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            <NavBar />
          </SignedIn>
          <SignedOut>
            <nav className="p-2 m-2 bg-red-800 text-white space-x-14 h-12 text-lg">
              <Link href="/">Home page</Link>
            </nav>
          </SignedOut>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
